[project]
name = "aiagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "00joaoguilherme", email = "joao.guilherme.bento.de.queiroz@ccc.ufcg.edu.br" }
]
requires-python = ">=3.14"
dependencies = [
    "openai==2.44.0",
    "python-dotenv==1.1.0",
]

[project.scripts]
aiagent = "aiagent:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
